### ISSUE TITLE
`x^0` does not simplify?

### ISSUE THREAD

**Issue by cortner** [dfdx/Espresso.jl#37]
Interesting package. 

```
julia> simplify( :( x^0 ) )
:(x ^ 0)
```
Is this intended? If so, then why?

EDIT: I can see that all I need to do is `@simple_rule (x^0) 1`, my question is just why this was omitted.

**Comment by dfdx** [comment]
It wasn't omitted, just nobody defined it :) 
I've added it to master, thanks for suggestion!
