### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by lbenet** [dfdx/Espresso.jl#38]
In v0.4.0, `Einsum.jl` is included in the `REQUIRE` file, and it seems to be responsible of some of our tests breaking in windows (see https://github.com/PerezHz/TaylorIntegration.jl/pull/31#issuecomment-383752650). Could you please tag a new (minor?) version, so we can update our `REQUIRE` file and see if our tests in windows also pass?

**Comment by dfdx** [comment]
Yep, sure, see JuliaLang/METADATA.jl#14372

**Comment by lbenet** [comment]
Thanks a lot!
