### ISSUE TITLE
Compatibility with Julia 1.0

### ISSUE THREAD

**Issue by lbenet** [dfdx/Espresso.jl#44]
I get [this error](https://travis-ci.org/PerezHz/TaylorIntegration.jl/jobs/426002275#L559) in Julia 1.0 but not in Julia 0.7. It would be nice to have full compatibility with Julia 1.0.

**Comment by dfdx** [comment]
Can you please test it with `]add Espresso#master`? I might have pushed a few commits after the latest release.

**Comment by lbenet** [comment]
Yes, `master` branch allows tests to pass in Julia 1.0. Thanks! I'll wait for the next release to update the REQUIRE file. Please ping me when you do it.

**Comment by dfdx** [comment]
Here's a [PR](https://github.com/JuliaLang/METADATA.jl/pull/17861) to METADATA. Once it's merged, a new version should be available.

**Comment by lbenet** [comment]
Thanks. I'll be following it. Why isn't it fully compatible? Is it related to the dependency on MacroTools?

**Comment by dfdx** [comment]
I think you misread release notes as "not fully compatible" though actually it says "now fully compatible". Or at least existing tests don't uncover any incompatibility :)

As for MacroTools, I've removed it from dependencies for now and just copied what I needed to [sugar.jl](https://github.com/dfdx/Espresso.jl/blob/master/src/sugar.jl) file.

**Comment by dfdx** [comment]
By the way, PR is merged, so I'm closing this issue. Please let me know if you find any other issues.

**Comment by lbenet** [comment]
Indeed, I misread it; thanks any way!
