### ISSUE TITLE
Issue in TaylorIntegration related to use of `Core.eval` in Espresso

### ISSUE THREAD

**Issue by PerezHz** [dfdx/Espresso.jl#49]
Hi @dfdx!

We have been dealing with an [issue](https://github.com/PerezHz/TaylorIntegration.jl/issues/106) in TaylorIntegration.jl without success, but we recently were able to trace it to a call to `Core.eval` in [this line](https://github.com/dfdx/Espresso.jl/blob/76c899cbd19df6f18e10875439591368fbc9b679/src/utils.jl#L151) of `Espresso.canonical`. As a workaround to the use of that `eval`, we implemented a specialized version of `ExGraph`, called `ExGraph_taylor`, as can be seen in [this PR](https://github.com/PerezHz/TaylorIntegration.jl/pull/113). I'm wondering if it would be possible to rewrite `canonical` without calling `Core.eval`? That would help us a lot to use our code in other modules... do you think there could be a way to achieve this?

**Comment by dfdx** [comment]
Hi! Please try `no-core-eval` branch of Espresso. It replaces `Core.eval(mod, qname)` with `getproperty(mod, qname)` in `canonical`, though there are other uses of `Core.eval()` which will be harder to remove. Let's see how much we need to change to make it work!

**Comment by PerezHz** [comment]
I just tried the `no-core-eval` branch and it works! Thanks a lot! We are looking forward to the next Espresso.jl release! 😄

**Comment by dfdx** [comment]
Version 0.6.1 has been released! Thanks for your help with it and let me know if you encounter any other issues!

**Comment by PerezHz** [comment]
Awesome! Really, thank you for fixing this and releasing the new version!
