### ISSUE TITLE
WARNING: could not import Base.Slot into Espresso

### ISSUE THREAD

**Issue by lbenet** [dfdx/Espresso.jl#52]
The following appeared today, after updating to Julia 1.10.5...

```julia
julia> using TaylorIntegration
Precompiling TaylorIntegration
  101 dependencies successfully precompiled in 22 seconds. 8 already precompiled.
  1 dependency had output during precompilation:
┌ Espresso
│  WARNING: could not import Base.Slot into Espresso
└  
```

**Comment by dfdx** [comment]
I _think_ I have fixed it. At least tests pass on 1.6, 1.10 and latest Julia without the warning. Please, update to Espresso 0.6.2 and check if has helped.

**Comment by lbenet** [comment]
There seems to be an issue with tagbot... see https://github.com/dfdx/Espresso.jl/issues/54#issuecomment-2321777379

**Comment by lbenet** [comment]
In any case, thanks a lot for addressing this!

**Comment by dfdx** [comment]
I had to push the new tag manually, but this worked for me just now:

```
pkg> add Espresso@v0.6.2
```

**Comment by dfdx** [comment]
I will assume that the issue is now fully resolved. Please re-open if there are other problems with it!
